version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install yarn packages
          command: 'yarn global add https://github.com/kojo-shopify/liquid-library-test-compiler'
      - run:
          name: Update PATH
          command: 'export PATH="$(yarn global bin):$PATH"'
      - run:
          name: Test path
          command: 'echo $PATH'
      - run:
          name: Build landing page README.md
          command: 'll_build_main'
      - run:
          name: Build component README.md
          command: 'll_build_cat'
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/liquid-library-test-compiler
