version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Global install ll-compiler
          command: 'yarn global add https://github.com/kojo-shopify/liquid-library-test-compiler'
      - run:
          name: Update $PATH to include yarn
          command: |
            echo 'export PATH=$HOME/.yarn/bin:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Build component README.md
          command: 'll_build_cat'
      - run:
          name: Build landing page README.md
          command: 'll_build_main'
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/liquid-library-test-compiler
      - deploy:
          name: Deploy to Github
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
                git config --global user.email "kojo.odapagyan@shopify.com"
                git config --global user.name "Kojo [CIRCLECI]"
                git add .
                git commit -m "CIRCLECI: project README files updated" || { echo 'Updates unnecessary'; exit 0; }
                git push origin master
            else
              echo "Not master: tests passed"
            fi
