version: 2
jobs:
  build_env:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install Yarn Packages
          command: 'yarn global add https://github.com/kojo-shopify/liquid-library-test-compiler'
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/liquid-library-test-compiler
  build_README:
    docker:
      - image: circleci/node
    steps:
      - restore_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "yarn.lock" }}
      - run:
          name: Check folder
          command: 'ls'
      - run:
          name: Build landing page README.md
          command: 'echo "hello"'
      - run:
          name: Build component README.md
          command: 'll_build_cat'
